---
title: "Bayesian workflow"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

### Bayesian workflow

Simulate the data
```{r}
set.seed(42)
library(extraDistr) # truncated poisson distribution
library(brms)
N <- 1000
id <- 1:N
nrepeat <- 7
pop_intercept <- 2.1 #
# "0-4" "5-14" "15+" 
age_grp <- sample(1:3, size=N, replace=TRUE, prob=c(0.12,0.18,0.70)) 
log_rr_age <- c(0, 0.53, -0.24)

random_error <- rnorm(N, mean=0, sd=0.03)

rand_intercept <- rnorm(N, mean=0, sd=0.6)

log_mean_contacts <- pop_intercept + log_rr_age[age_grp] + 
  random_error + rand_intercept

contacts <- as.vector(replicate(nrepeat, 
                      rtpois(N, lambda=exp(log_mean_contacts), a=0, b=60)))


d <- data.frame(id = rep(as.character(id), nrepeat),
                contacts = contacts, 
                age_grp = rep(as.factor(age_grp), nrepeat))

```

EDA
```{r}
hist(d$contacts, breaks=61)
var(d$contacts)/mean(d$contacts)
```

Priors
```{r}
set_prior("normal(0, 5)", class = "Intercept")
set_prior("normal(0, 1)", class = "b")
prior_string("cauchy(0, 5)", class = "sd")
```
Model fitting
```{r, eval=FALSE}
# fit_prior <- brm(contacts ~ age_grp + (1|id),
#         data = d, family = poisson(), 
#         iter = 1000, warmup = 500, cores = 4, sample_prior = "only",
#         prior = c(prior(normal(0, 3), class = "Intercept"),
#                   prior(normal(0, 1), class = "b", coef="age_grp2"),
#                   prior(normal(0, 1), class = "sd")))
# 
# fit_pois <- brm(contacts ~ age_grp,
#         data = d, family = poisson(), 
#         iter = 1000, warmup = 500, cores = 4, sample_prior = TRUE)
# 
# fit_mix_pois <- brm(contacts ~ age_grp + (1|id),
#         data = d, family = poisson(), 
#         iter = 1000, warmup = 500, cores = 4, sample_prior = TRUE)
# 
# saveRDS(fit_prior, "outputs/baye_workflow_fit_prior_20240610.rds")
# saveRDS(fit_pois, "outputs/baye_workflow_fit_pois_20240610.rds")
# saveRDS(fit_mix_pois, "outputs/baye_workflow_fit_mix_pois_20240610.rds")
```

Prior predictive check
```{r}
draws1 <- prior_draws(fit_prior)

fit <- readRDS("outputs/baye_workflow_fit_pois_20240610.rds")
fit_prior <- readRDS("outputs/baye_workflow_fit_prior_20240610.rds")
fit_mix <- readRDS("outputs/baye_workflow_fit_mix_pois_20240610.rds")

prior_ppc <- posterior_predict(fit_prior, ndraws = 1000)
plot(density(prior_ppc[1,]), xlim=c(0,60), ylim=c(0,2), col="grey70")
for (i in 2:1000) {
  lines(density(prior_ppc[i,]), col="grey70")
}

ppc_glm <- posterior_predict(fit, ndraws = 1000)
for (i in 1:1000) {
  lines(density(ppc_glm[i,]), col="steelblue")
}

ppc <- posterior_predict(fit_mix, ndraws = 1000)
for (i in 1:1000) {
  lines(density(ppc[i,]), col="darkred")
}

# data
lines(density(fit$data$contacts), col="green", lwd=2)

```


```{r}

fit <- brm(rating ~ treat + period + carry + (1|subject),
           data = inhaler, family = "cumulative",
           prior = set_prior("normal(0,2)", class = "b"),
           sample_prior = TRUE)

# extract all prior draws
draws1 <- prior_draws(fit)
head(draws1)

# extract prior draws for the coefficient of 'treat'
draws2 <- prior_draws(fit, "b_treat")
head(draws2)
```

Posterior predictive check
```{r}
library(bayesplot)
color_scheme_set("red")
ppc_dens_overlay(y = fit_pois$data$contacts,
                 yrep = posterior_predict(fit_pois, draws = 50))
color_scheme_set("viridis")
plt2 <- ppc_dens_overlay(y = fit_pois$data$contacts,
                 yrep = posterior_predict(fit_mix_pois, draws = 50))
plt2 + theme_bw()
```




GLM not accounting for repeated measures
```{r}
tic <- Sys.time()


fit_mix_pois <- brms::brm(contacts ~ age_grp, data = d, 
                family = poisson(), iter = 1000, warmup = 500, cores = 4)
Sys.time() - tic

fit_mix_nb <- brms::brm(contacts ~ age_grp, data = d, 
                family = negbinomial(), iter = 1000, warmup = 500, cores = 4)
Sys.time() - tic


library(bayesplot)
ppc_dens_overlay(y = fit_mix_pois$contacts,
                 yrep = posterior_predict(fit_mix_pois, draws = 1000))
```

Bayesian GLMM
```{r}
tic <- Sys.time()

fit_mix_pois <- brms::brm(events ~ age_grp + (1|id), data = d, 
                family = poisson(), iter = 1000, warmup = 500, cores = 4)
Sys.time() - tic

```

